### PR TITLE
Many tweaks and subjectively helpful changes.

### PR DESCRIPTION
**Pull request by Doug-Murphy**
- Add a few helpful changes like a custom exception type.
- Made some updates to the NuGet tags and other things in the .csproj

### CODE REVIEW

**Review by at0dd — CHANGES_REQUESTED** [review]
Thanks for the PR! I think the only thing I would change is the renaming of variables to `Id` - uppercase `ID` is used in all of the models.

**Comment by Doug-Murphy** [comment]
I have reverted the ID -> Id changes.

Now that .NET 7 is released, I went ahead and added that in (and dropped .NET 5 since it hit EOL a few months ago).

**Comment by Doug-Murphy** [comment]
@at0dd It looks like CodeQL doesn't support .NET 7. :) Would you rather remove that TFM or bypass the CodeQL scan for this PR since it's still able to scan it for the other TFM builds?

**Comment by at0dd** [comment]
Let's remove .NET 7 for now and I'll add it once it gets more support.

**Comment by Doug-Murphy** [comment]
@at0dd I have removed .NET 7. Should be good to go now!

**Review by at0dd — APPROVED** [review]

**Pull request merged**
